-- StemRobin database schema — SSOT for the project's Postgres tables.
--
-- Platform: the Azure easy-app SHARED Postgres provisioned for this project by
-- n-easyapp cap1 at first deploy (server `pg-easyapp-shared`, database `easyapp`,
-- per-project schema `stemrobin-schema`, role `stemrobin-user`). This project no
-- longer uses Supabase. The schema/role already exist — this file only creates
-- tables and seeds. Apply with the easy-app connection string (server-only):
--
--   psql "$EASYAPP_DATABASE_URL" -f ssot-schemas/db-schemas/stemrobin.sql
--
-- Access model: plain Postgres, no PostgREST/RLS anon layer. All reads/writes go
-- through server-side code holding the connection string; the browser never has it.

SET search_path TO "stemrobin-schema";

-- ---------------------------------------------------------------------------
-- sr_users — learner identity. Minimal by design: the only auth this stage is a
-- single preset learner used to save answer state. Full auth (Clerk) is future.
-- Password is stored ONLY as a scrypt hash (see app/src/lib/auth.ts), never plaintext.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sr_users (
  user_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email          TEXT UNIQUE NOT NULL,
  password_hash  TEXT NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- sr_lessons — one row per lesson. `html` holds the 課文 (self-contained lesson
-- HTML: KaTeX + inline SVG + DESIGN tokens). Stored here, not in local files.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sr_lessons (
  id             TEXT PRIMARY KEY,                 -- e.g. 'math-s3-03'
  subject        TEXT NOT NULL CHECK (subject IN ('math','physics')),
  stage          INT  NOT NULL,
  lesson_order   INT  NOT NULL,
  title          TEXT NOT NULL,
  concept        TEXT NOT NULL,
  html           TEXT,                             -- 課文 HTML
  pdf            BYTEA,                             -- pre-generated print PDF bytes
  status         TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published')),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (subject, stage, lesson_order)
);

-- ---------------------------------------------------------------------------
-- sr_questions — structured practice items (the card-quiz deck). Modes:
-- 'choice' sets options/correct_index; 'input' sets accept (typed-answer forms,
-- normalized server-side); 'work' is open response. `layer` is the deck role
-- (指认/操作/辨错/说理/复习) and `review_of` names the earlier-lesson term a
-- 复习 item refreshes (spaced review baked in at generation time).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sr_questions (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lesson_id      TEXT NOT NULL REFERENCES sr_lessons(id) ON DELETE CASCADE,
  ord            INT  NOT NULL,
  type           TEXT NOT NULL,                    -- 辨认/表示/操作/反推/辨错/说理
  prompt         TEXT NOT NULL,                    -- question text (KaTeX)
  answer_mode    TEXT NOT NULL CHECK (answer_mode IN ('choice','work','input')),
  options        JSONB,                            -- choice only: ["opt A", ...]
  correct_index  INT,                              -- choice only: index into options
  accept         JSONB,                            -- input only: accepted answer strings
  layer          TEXT,                             -- deck role: 指认/操作/辨错/说理/复习
  review_of      TEXT,                             -- 复习 only: term being refreshed
  answer         TEXT NOT NULL,                    -- hidden explanation (post-answer reveal)
  UNIQUE (lesson_id, ord)
);

CREATE INDEX IF NOT EXISTS sr_questions_lesson_idx ON sr_questions (lesson_id, ord);

-- ---------------------------------------------------------------------------
-- sr_answer_events — one row per attempt. References only the question id (the
-- lesson is derived via the question). Covers both types: choice answers set
-- `chosen` + `is_correct`; work answers (future) set `answer_blob_id` (the answer
-- photo). `answer_blob_id` is a nullable forward-compat slot, unused this stage.
-- Every wrong answer stays traceable per learner and question (weakness analysis).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sr_answer_events (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        BIGINT NOT NULL REFERENCES sr_users(user_id) ON DELETE CASCADE,
  question_id    BIGINT NOT NULL REFERENCES sr_questions(id) ON DELETE CASCADE,
  is_correct     BOOLEAN,
  chosen         INT,                              -- chosen option index (choice)
  answer_text    TEXT,                             -- typed answer (input mode)
  answer_blob_id TEXT,                             -- future work-answer photo blob id
  answered_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS sr_answer_events_user_idx
  ON sr_answer_events (user_id, question_id);

-- ---------------------------------------------------------------------------
-- sr_quiz_attempts — one "答题" (a pass through a lesson's card-quiz) per row.
-- A learner has at most one in-progress attempt per lesson (ended_at IS NULL);
-- clicking 结束本课答题 stamps ended_at, freezing it as the scorecard. The most
-- recent ended attempt is what "上一次成绩" shows; a new ended attempt supersedes
-- it (we always read the latest, so ending refreshes the scorecard). Answer
-- events link back via sr_answer_events.attempt_id so a score / resume can be
-- reconstructed. Restarting (重新开始) deletes the open attempt and its events.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sr_quiz_attempts (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        BIGINT NOT NULL REFERENCES sr_users(user_id) ON DELETE CASCADE,
  lesson_id      TEXT   NOT NULL REFERENCES sr_lessons(id) ON DELETE CASCADE,
  started_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  ended_at       TIMESTAMPTZ                        -- NULL = in progress
);

CREATE INDEX IF NOT EXISTS sr_quiz_attempts_user_lesson_idx
  ON sr_quiz_attempts (user_id, lesson_id, ended_at);

-- Link each answer event to its attempt (nullable: story-quiz events and legacy
-- rows carry none). ON DELETE CASCADE so 重新开始 wiping an attempt clears its events.
ALTER TABLE sr_answer_events
  ADD COLUMN IF NOT EXISTS attempt_id BIGINT REFERENCES sr_quiz_attempts(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS sr_answer_events_attempt_idx
  ON sr_answer_events (attempt_id);

-- ---------------------------------------------------------------------------
-- sr-story tables — 创造者档案 (public-domain biography reading). Written ONLY by
-- .agents/skills/sr-story/scripts/save-story.mjs (cap5). Mirror the lesson tables:
-- a story (creator/book) has ordered chapters, each chapter its own card-quiz
-- questions. `html` is the self-contained chapter reading HTML (same shell as
-- lessons). Sources MUST be public domain — `source_url` records provenance.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sr_stories (
  id          TEXT PRIMARY KEY,                 -- slug, e.g. 'franklin'
  title       TEXT NOT NULL,
  person      TEXT NOT NULL,
  era         TEXT,                             -- e.g. '1706–1790'
  source_url  TEXT NOT NULL,                    -- public-domain source (Gutenberg/Archive)
  status      TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sr_story_chapters (
  id          TEXT PRIMARY KEY,                 -- e.g. 'ford-c01'
  story_id    TEXT NOT NULL REFERENCES sr_stories(id) ON DELETE CASCADE,
  ord         INT  NOT NULL,
  title       TEXT NOT NULL,
  md          TEXT,                             -- chapter body as Markdown (app renders md → html)
  status      TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published')),
  -- staged/section structure (batch 0002): chapters group into named 阶段 (stage),
  -- each chapter divides into numbered 节 whose numbers are GLOBALLY CONTINUOUS across
  -- the whole biography (a reader can cite "§N" and locate it fast).
  stage         TEXT,                           -- 阶段 label, e.g. '少年与机械'; NULL = ungrouped
  stage_ord     INT,                            -- stage order for grouping/sorting
  section_start INT,                            -- global number of this chapter's first 节
  section_end   INT,                            -- global number of this chapter's last 节
  pdf         BYTEA,                             -- pre-rendered print PDF (like sr_lessons.pdf)
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (story_id, ord)
);

CREATE INDEX IF NOT EXISTS sr_story_chapters_story_idx ON sr_story_chapters (story_id, ord);

-- Mirrors sr_questions: `options`/`correct_index` set only when answer_mode='choice';
-- `answer` is the hidden reference answer. type ∈ 理解/推断/创业推理/品格/辨错 (free text).
CREATE TABLE IF NOT EXISTS sr_story_questions (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chapter_id     TEXT NOT NULL REFERENCES sr_story_chapters(id) ON DELETE CASCADE,
  ord            INT  NOT NULL,
  type           TEXT NOT NULL,
  prompt         TEXT NOT NULL,
  answer_mode    TEXT NOT NULL CHECK (answer_mode IN ('choice','work')),
  options        JSONB,
  correct_index  INT,
  answer         TEXT NOT NULL,
  UNIQUE (chapter_id, ord)
);

CREATE INDEX IF NOT EXISTS sr_story_questions_chapter_idx
  ON sr_story_questions (chapter_id, ord);

-- Mirrors sr_answer_events for story questions. Separate table because
-- sr_answer_events.question_id FKs to sr_questions(id); story questions are a
-- distinct id-space in sr_story_questions. Written by recordStoryAnswer.
CREATE TABLE IF NOT EXISTS sr_story_answer_events (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        BIGINT NOT NULL REFERENCES sr_users(user_id) ON DELETE CASCADE,
  question_id    BIGINT NOT NULL REFERENCES sr_story_questions(id) ON DELETE CASCADE,
  is_correct     BOOLEAN,
  chosen         INT,                              -- chosen option index (choice)
  answer_blob_id TEXT,                             -- future work-answer photo blob id
  answered_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS sr_story_answer_events_user_idx
  ON sr_story_answer_events (user_id, question_id);

-- ===========================================================================
-- JSONB CONTENT SSOT (STEMROBIN-19, batch 0004-jsonb-card-reading)
-- ---------------------------------------------------------------------------
-- Makes the DB the single authority for course content as JSONB. Three neutral,
-- language-neutral JSONB families are the SSOT; HTML/卡片视图/PDF and every locale
-- are DERIVED (regenerable) from them:
--   1. ledger   — per (subject, stage), in sr_content_ledger
--   2. content  — per lesson card-tree, in sr_lessons.content
--   3. exercises— per lesson deck, in sr_lessons.exercises
-- Learner-facing prose is NOT stored in the neutral base; it lives in a per-locale
-- text overlay (sr_lesson_i18n) keyed by node_id. The answer KEY (correct option /
-- accepted forms / reference answer) lives ONLY in the neutral base JSONB and is
-- structurally excluded from every locale overlay (answer-key secrecy). Card and
-- exercise answer events are stored in sr_content_answer_events (disposable data).
--
-- This ticket is SCHEMA ONLY: it defines structure, not the generator, migration,
-- reading UI, or translation (STEMROBIN-20..24). Existing rows keep NULL content
-- until a later migration populates them. All statements are additive + idempotent.
-- The internal JSONB shapes below (cards[].read_check[].key, exercises.items[].key,
-- per-node `rev` / overlay `src_rev`) are a CONTRACT documented here and enforced by
-- the generator/saver/reader tickets — Postgres does not constrain JSONB internals.
-- ===========================================================================

-- Neutral base content on the existing lesson identity row. Added via ALTER (the
-- table already exists in prod, so a CREATE TABLE IF NOT EXISTS block would no-op).
-- html/pdf on sr_lessons remain DERIVED caches; SSOT for content = these columns.
--
--   content   = { "cards": [ {
--                   "id": "<stable card node id>", "num": <learner-visible 编号>,
--                   "anchor": "motivation|model|anatomy|boundary|explain|examples|connections|...",
--                   "rev": <int>,                       -- per-node source revision (staleness)
--                   "body": [ <ordered neutral nodes> ],-- prose nodes are node-id refs (text in overlay);
--                                                         -- formula (KaTeX) / svg nodes are neutral, inline here
--                   "read_check": [ {
--                       "id": "<stable check node id>", "mode": "choice"|"input",
--                       "key": { "correct_index": <int> } | { "accept": ["…"] },  -- KEY: neutral-base only
--                       "rev": <int>
--                   } ]
--                 } ] }
--   exercises = { "items": [ {
--                   "id": "<stable item node id>", "ord": <int>, "type": "辨认|表示|操作|反推|辨错|说理",
--                   "mode": "choice"|"input"|"work", "layer": "指认|操作|辨错|说理|复习",
--                   "review_of": "<earlier term>"|null,
--                   "key": { "correct_index": <int> } | { "accept": ["…"] } | { "answer": "<reference>" },
--                   "rev": <int>
--                 } ] }
-- Prose text is NOT stored here; only structure/order/编号/anchors/formulas/SVG/KEY.
ALTER TABLE sr_lessons ADD COLUMN IF NOT EXISTS content   JSONB;  -- neutral card-tree SSOT
ALTER TABLE sr_lessons ADD COLUMN IF NOT EXISTS exercises JSONB;  -- neutral exercise-deck SSOT

-- Per-stage concept ledger, migrated from resources/content/math-ledger/stage-*.json
-- into the DB as the authoritative source. Authoring metadata (source language zh);
-- NOT part of the learner-facing i18n overlay (ledger prose is not translated).
--   ledger = { subject, stage, theme, model, assumed[], lessons[] { id, order, title,
--              genre, status, core_idea, introduces[], consumes[], boundary_cases[] } }
CREATE TABLE IF NOT EXISTS sr_content_ledger (
  subject     TEXT NOT NULL,
  stage       INT  NOT NULL,
  ledger      JSONB NOT NULL,                         -- the concept-ledger document, verbatim
  src_rev     BIGINT NOT NULL DEFAULT 1,              -- ledger source revision
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (subject, stage)
);

-- Per-locale text overlay: ONE overlay per (lesson, locale). Maps each translatable
-- prose node_id to its translated string plus the source revision it was translated
-- from (staleness ⇔ overlay src_rev < neutral-base node rev, or node absent). zh is
-- the SOURCE locale and is itself an overlay row. This table holds ONLY prose — it
-- MUST NEVER contain an answer KEY (correct_index / accept / answer). Formulas/SVG/
-- numeric literals inherit from the neutral base and are never duplicated here.
--   overlay = { "<node_id>": { "t": "<translated prose>", "src_rev": <int> } }
CREATE TABLE IF NOT EXISTS sr_lesson_i18n (
  lesson_id   TEXT NOT NULL REFERENCES sr_lessons(id) ON DELETE CASCADE,
  locale      TEXT NOT NULL,                          -- 'zh' (source) | 'en' | …
  overlay     JSONB NOT NULL,                         -- { node_id -> { t, src_rev } }, prose only, NO KEY
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (lesson_id, locale)
);

-- Card read-check + exercise answer events. One table with a `kind` discriminator
-- (read-check and exercise events share an identical shape). node_id is the JSONB
-- item identity (a read_check id or an exercises item id) — there is deliberately NO
-- FK to a relational question row, because JSONB items have no row identity. This
-- answer-event data is DISPOSABLE (authorized). is_correct is null for ungraded
-- (work) items; chosen is the choice option index; answer_text is typed input.
CREATE TABLE IF NOT EXISTS sr_content_answer_events (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      BIGINT NOT NULL REFERENCES sr_users(user_id) ON DELETE CASCADE,
  lesson_id    TEXT   NOT NULL REFERENCES sr_lessons(id) ON DELETE CASCADE,
  kind         TEXT   NOT NULL CHECK (kind IN ('read_check','exercise')),
  node_id      TEXT   NOT NULL,                        -- read_check id or exercises item id (JSONB identity)
  is_correct   BOOLEAN,                                -- null = ungraded (work)
  chosen       INT,                                    -- choice option index
  answer_text  TEXT,                                   -- typed input text
  locale       TEXT,                                   -- locale the learner answered in (disposable analytics)
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS sr_content_answer_events_user_lesson_idx
  ON sr_content_answer_events (user_id, lesson_id);
