-- StemRobin database schema — SSOT for the project's Postgres tables.
--
-- Platform: the Azure easy-app SHARED Postgres provisioned for this project by
-- n-easyapp cap1 at first deploy (server `pg-easyapp-shared`, database `easyapp`,
-- per-project schema `stemrobin-schema`, role `stemrobin-user`). This project no
-- longer uses Supabase. The schema/role already exist — this file only creates
-- tables and seeds. Apply with the easy-app connection string (server-only):
--
--   psql "$EASYAPP_DATABASE_URL" -f ssot-schemas/db-schemas/stemrobin.sql
--
-- Access model: plain Postgres, no PostgREST/RLS anon layer. All reads/writes go
-- through server-side code holding the connection string; the browser never has it.

SET search_path TO "stemrobin-schema";

-- ---------------------------------------------------------------------------
-- sr_users — learner identity. Minimal by design: the only auth this stage is a
-- single preset learner used to save answer state. Full auth (Clerk) is future.
-- Password is stored ONLY as a scrypt hash (see app/src/lib/auth.ts), never plaintext.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sr_users (
  user_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email          TEXT UNIQUE NOT NULL,
  password_hash  TEXT NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- sr_lessons — one row per lesson. `html` holds the 課文 (self-contained lesson
-- HTML: KaTeX + inline SVG + DESIGN tokens). Stored here, not in local files.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sr_lessons (
  id             TEXT PRIMARY KEY,                 -- e.g. 'math-s3-03'
  subject        TEXT NOT NULL CHECK (subject IN ('math','physics')),
  stage          INT  NOT NULL,
  lesson_order   INT  NOT NULL,
  title          TEXT NOT NULL,
  concept        TEXT NOT NULL,
  html           TEXT,                             -- 課文 HTML
  pdf            BYTEA,                             -- pre-generated print PDF bytes
  status         TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published')),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (subject, stage, lesson_order)
);

-- ---------------------------------------------------------------------------
-- sr_questions — structured practice items (the card-quiz deck). Modes:
-- 'choice' sets options/correct_index; 'input' sets accept (typed-answer forms,
-- normalized server-side); 'work' is open response. `layer` is the deck role
-- (指认/操作/辨错/说理/复习) and `review_of` names the earlier-lesson term a
-- 复习 item refreshes (spaced review baked in at generation time).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sr_questions (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lesson_id      TEXT NOT NULL REFERENCES sr_lessons(id) ON DELETE CASCADE,
  ord            INT  NOT NULL,
  type           TEXT NOT NULL,                    -- 辨认/表示/操作/反推/辨错/说理
  prompt         TEXT NOT NULL,                    -- question text (KaTeX)
  answer_mode    TEXT NOT NULL CHECK (answer_mode IN ('choice','work','input')),
  options        JSONB,                            -- choice only: ["opt A", ...]
  correct_index  INT,                              -- choice only: index into options
  accept         JSONB,                            -- input only: accepted answer strings
  layer          TEXT,                             -- deck role: 指认/操作/辨错/说理/复习
  review_of      TEXT,                             -- 复习 only: term being refreshed
  answer         TEXT NOT NULL,                    -- hidden explanation (post-answer reveal)
  UNIQUE (lesson_id, ord)
);

CREATE INDEX IF NOT EXISTS sr_questions_lesson_idx ON sr_questions (lesson_id, ord);

-- ---------------------------------------------------------------------------
-- sr_answer_events — one row per attempt. References only the question id (the
-- lesson is derived via the question). Covers both types: choice answers set
-- `chosen` + `is_correct`; work answers (future) set `answer_blob_id` (the answer
-- photo). `answer_blob_id` is a nullable forward-compat slot, unused this stage.
-- Every wrong answer stays traceable per learner and question (weakness analysis).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sr_answer_events (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        BIGINT NOT NULL REFERENCES sr_users(user_id) ON DELETE CASCADE,
  question_id    BIGINT NOT NULL REFERENCES sr_questions(id) ON DELETE CASCADE,
  is_correct     BOOLEAN,
  chosen         INT,                              -- chosen option index (choice)
  answer_text    TEXT,                             -- typed answer (input mode)
  answer_blob_id TEXT,                             -- future work-answer photo blob id
  answered_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS sr_answer_events_user_idx
  ON sr_answer_events (user_id, question_id);

-- ---------------------------------------------------------------------------
-- sr-story tables — 创造者档案 (public-domain biography reading). Written ONLY by
-- .agents/skills/sr-story/scripts/save-story.mjs (cap5). Mirror the lesson tables:
-- a story (creator/book) has ordered chapters, each chapter its own card-quiz
-- questions. `html` is the self-contained chapter reading HTML (same shell as
-- lessons). Sources MUST be public domain — `source_url` records provenance.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sr_stories (
  id          TEXT PRIMARY KEY,                 -- slug, e.g. 'franklin'
  title       TEXT NOT NULL,
  person      TEXT NOT NULL,
  era         TEXT,                             -- e.g. '1706–1790'
  source_url  TEXT NOT NULL,                    -- public-domain source (Gutenberg/Archive)
  status      TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sr_story_chapters (
  id          TEXT PRIMARY KEY,                 -- e.g. 'ford-c01'
  story_id    TEXT NOT NULL REFERENCES sr_stories(id) ON DELETE CASCADE,
  ord         INT  NOT NULL,
  title       TEXT NOT NULL,
  md          TEXT,                             -- chapter body as Markdown (app renders md → html)
  status      TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (story_id, ord)
);

CREATE INDEX IF NOT EXISTS sr_story_chapters_story_idx ON sr_story_chapters (story_id, ord);

-- Mirrors sr_questions: `options`/`correct_index` set only when answer_mode='choice';
-- `answer` is the hidden reference answer. type ∈ 理解/推断/创业推理/品格/辨错 (free text).
CREATE TABLE IF NOT EXISTS sr_story_questions (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chapter_id     TEXT NOT NULL REFERENCES sr_story_chapters(id) ON DELETE CASCADE,
  ord            INT  NOT NULL,
  type           TEXT NOT NULL,
  prompt         TEXT NOT NULL,
  answer_mode    TEXT NOT NULL CHECK (answer_mode IN ('choice','work')),
  options        JSONB,
  correct_index  INT,
  answer         TEXT NOT NULL,
  UNIQUE (chapter_id, ord)
);

CREATE INDEX IF NOT EXISTS sr_story_questions_chapter_idx
  ON sr_story_questions (chapter_id, ord);

-- Mirrors sr_answer_events for story questions. Separate table because
-- sr_answer_events.question_id FKs to sr_questions(id); story questions are a
-- distinct id-space in sr_story_questions. Written by recordStoryAnswer.
CREATE TABLE IF NOT EXISTS sr_story_answer_events (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        BIGINT NOT NULL REFERENCES sr_users(user_id) ON DELETE CASCADE,
  question_id    BIGINT NOT NULL REFERENCES sr_story_questions(id) ON DELETE CASCADE,
  is_correct     BOOLEAN,
  chosen         INT,                              -- chosen option index (choice)
  answer_blob_id TEXT,                             -- future work-answer photo blob id
  answered_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS sr_story_answer_events_user_idx
  ON sr_story_answer_events (user_id, question_id);
