/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as EnglishAudioIdRouteImport } from './routes/english-audio.$id'
import { Route as AppLessonIdRouteImport } from './routes/_app/lesson.$id'
import { Route as AppEnglishIdRouteImport } from './routes/_app/english.$id'
import { Route as AppEnglishIdReciteRouteImport } from './routes/_app/english.$id_.recite'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const EnglishAudioIdRoute = EnglishAudioIdRouteImport.update({
  id: '/english-audio/$id',
  path: '/english-audio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLessonIdRoute = AppLessonIdRouteImport.update({
  id: '/lesson/$id',
  path: '/lesson/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEnglishIdRoute = AppEnglishIdRouteImport.update({
  id: '/english/$id',
  path: '/english/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEnglishIdReciteRoute = AppEnglishIdReciteRouteImport.update({
  id: '/english/$id_/recite',
  path: '/english/$id/recite',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/english-audio/$id': typeof EnglishAudioIdRoute
  '/english/$id': typeof AppEnglishIdRoute
  '/lesson/$id': typeof AppLessonIdRoute
  '/english/$id/recite': typeof AppEnglishIdReciteRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/english-audio/$id': typeof EnglishAudioIdRoute
  '/': typeof AppIndexRoute
  '/english/$id': typeof AppEnglishIdRoute
  '/lesson/$id': typeof AppLessonIdRoute
  '/english/$id/recite': typeof AppEnglishIdReciteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/english-audio/$id': typeof EnglishAudioIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/english/$id': typeof AppEnglishIdRoute
  '/_app/lesson/$id': typeof AppLessonIdRoute
  '/_app/english/$id_/recite': typeof AppEnglishIdReciteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/english-audio/$id'
    | '/english/$id'
    | '/lesson/$id'
    | '/english/$id/recite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/english-audio/$id'
    | '/'
    | '/english/$id'
    | '/lesson/$id'
    | '/english/$id/recite'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/english-audio/$id'
    | '/_app/'
    | '/_app/english/$id'
    | '/_app/lesson/$id'
    | '/_app/english/$id_/recite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  EnglishAudioIdRoute: typeof EnglishAudioIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/english-audio/$id': {
      id: '/english-audio/$id'
      path: '/english-audio/$id'
      fullPath: '/english-audio/$id'
      preLoaderRoute: typeof EnglishAudioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/lesson/$id': {
      id: '/_app/lesson/$id'
      path: '/lesson/$id'
      fullPath: '/lesson/$id'
      preLoaderRoute: typeof AppLessonIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/english/$id': {
      id: '/_app/english/$id'
      path: '/english/$id'
      fullPath: '/english/$id'
      preLoaderRoute: typeof AppEnglishIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/english/$id_/recite': {
      id: '/_app/english/$id_/recite'
      path: '/english/$id/recite'
      fullPath: '/english/$id/recite'
      preLoaderRoute: typeof AppEnglishIdReciteRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppEnglishIdRoute: typeof AppEnglishIdRoute
  AppLessonIdRoute: typeof AppLessonIdRoute
  AppEnglishIdReciteRoute: typeof AppEnglishIdReciteRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppEnglishIdRoute: AppEnglishIdRoute,
  AppLessonIdRoute: AppLessonIdRoute,
  AppEnglishIdReciteRoute: AppEnglishIdReciteRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  EnglishAudioIdRoute: EnglishAudioIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
