// The landing page: a white page whose one dark surface is the knowledge
// galaxy, so the map reads as the product and the words read as the argument.
//
// It sits outside the `_app` layout, so the catalog rail does not appear here.
// "Start learning" hands over to /learn, which is inside that layout — that is
// where the rail, the deck numbers and the lessons live. Class prefix `lw-`.

import { useEffect, useRef, useState } from 'react'
import { Link, createFileRoute, useRouter } from '@tanstack/react-router'
import { Menu, Minus, Plus, Search, X } from 'lucide-react'

import { KnowledgeGalaxy, type GalaxyApi } from '~/components/knowledge-galaxy'
import {
  bookLessons,
  getTextbookOutline,
  type OutlineLesson,
  type OutlineNode,
} from '~/lib/textbooks'
import { listAvailableLessonIds } from '~/lib/lessons'
import { getLocale, setLocale } from '~/lib/locale'

export const Route = createFileRoute('/')({
  component: LandingLight,
  loader: async () => ({
    locale: await getLocale(),
    lessonIds: await listAvailableLessonIds(),
  }),
})

const COPY = {
  en: {
    brandSub: 'The Lemma to Science',
    navMap: 'Curriculum map',
    signIn: 'Sign in',
    startFree: 'Start learning free',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    langButton: '中文',
    ready: (n: number) => `${n} lessons ready`,
    comingSoon: 'Coming soon',
    searchPlaceholder: 'Search course units…',
    mapHint: 'Zoom, pan, and see how knowledge connects.',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    reset: 'Reset view',

    h1: 'A complete secondary-school course in mathematics and physics.',
    lead: 'Built on the ten-year science curriculum led by Andrey Kolmogorov and the rigour of twentieth-century education.',
    body: 'More than 1,500 teaching units and 16,000 exercises form an interconnected body of knowledge, adapted to your progress.',
    outcome:
      'Complete the course to prepare for university entrance examinations and further study in mathematics, science and engineering.',

    quote:
      '“School mathematics, and even the beginnings of calculus, can be mastered by ordinary ability — given good guidance or good books.”',
    quoteBy: '— Andrey Kolmogorov',
    quoteByTitle: 'One of the Greatest Mathematicians of the 20th Century',

    pointsTitle: 'What sets it apart',
    points: [
      'Rigorous, systematic lessons and exercises written by experts — not generated by AI.',
      'It locates the weakness itself, instead of patching one problem at a time.',
      'Unlimited explanation and fresh practice at your own pace, until it is genuinely yours.',
      'Fill a gap or run ahead — not bound to your school’s timetable.',
    ],

    ctaTitle: 'Start anywhere on the chain.',
    ctaSecondary: 'Open the curriculum map',
  },
  zh: {
    brandSub: '引理阶梯 · 通向科学的引理',
    navMap: '课程地图',
    signIn: '登录',
    startFree: '免费开始学习',
    openMenu: '打开菜单',
    closeMenu: '关闭菜单',
    langButton: 'EN',
    ready: (n: number) => `${n} 节课已上线`,
    comingSoon: '即将上线',
    searchPlaceholder: '搜索课程单元……',
    mapHint: '缩放、平移，看见知识如何相连。',
    zoomIn: '放大',
    zoomOut: '缩小',
    reset: '复位视角',

    h1: '一套完整的中学数学与物理课程。',
    lead: '基于柯尔莫戈洛夫主导制定的十年制理科大纲，植根于 20 世纪严谨的教育传统。',
    body: '1,500 多个教学单元和 16,000 多道习题，构成一个环环相扣的知识宇宙，并根据你的学习进度自适应呈现。',
    outcome:
      '完成这套课程，你将能够从容应对大学入学考试，并为继续学习数学、科学与工程打下坚实的基础。',

    quote: '“中学数学，乃至微积分的基础，在良好的指导或优秀书籍的帮助下，普通的能力就足以掌握。”',
    quoteBy: '——安德烈·柯尔莫戈洛夫',
    quoteByTitle: '20 世纪最伟大的数学家之一',

    pointsTitle: '特点',
    points: [
      '专家编写的严谨、系统的课程与练习，非 AI 生成。',
      '精确定位薄弱环节，而不是孤立解决单个问题。',
      'AI 根据你的进度无限讲解、生成同类练习，直到真正掌握。',
      '既可补弱，也可超前，不受学校进度限制。',
    ],

    ctaTitle: '从这条链上的任何一处开始。',
    ctaSecondary: '打开课程地图',
  },
} as const

function LandingLight() {
  const { locale, lessonIds } = Route.useLoaderData()
  const router = useRouter()
  const t = COPY[locale]
  const [menuOpen, setMenuOpen] = useState(false)
  const [navOpen, setNavOpen] = useState(false)
  const [query, setQuery] = useState('')
  const [openBook, setOpenBook] = useState<string | null>(null)
  const [mapReady, setMapReady] = useState(false)
  const navRef = useRef<HTMLElement>(null)
  const galaxyRef = useRef<GalaxyApi | null>(null)

  const outline = getTextbookOutline(lessonIds, locale)

  useEffect(() => {
    if (!menuOpen) return
    const onDown = (e: MouseEvent) => {
      if (navRef.current && !navRef.current.contains(e.target as Node)) setMenuOpen(false)
    }
    const onKey = (e: KeyboardEvent) => e.key === 'Escape' && setMenuOpen(false)
    document.addEventListener('mousedown', onDown)
    document.addEventListener('keydown', onKey)
    return () => {
      document.removeEventListener('mousedown', onDown)
      document.removeEventListener('keydown', onKey)
    }
  }, [menuOpen])

  useEffect(() => {
    if (!navOpen) return
    const onKey = (e: KeyboardEvent) => e.key === 'Escape' && setNavOpen(false)
    document.addEventListener('keydown', onKey)
    return () => document.removeEventListener('keydown', onKey)
  }, [navOpen])

  async function switchLocale() {
    await setLocale({ data: locale === 'zh' ? 'en' : 'zh' })
    await router.invalidate()
  }

  const q = query.trim().toLowerCase()
  const matches =
    q && galaxyRef.current
      ? galaxyRef.current.stars
          .map((star, index) => ({ star, index }))
          .filter(
            ({ star }) =>
              star.title.toLowerCase().includes(q) ||
              (star.titleEn ?? '').toLowerCase().includes(q),
          )
          .slice(0, 8)
      : []

  // Volumes on the left, the chosen volume's chapters and numbered sections on
  // the right. Unnumbered matter — closing problem sets, appendices — belongs
  // in the lesson, not in a nav panel.
  const allBooks = outline.flatMap((d) => d.books)
  const activeBook = allBooks.find((b) => b.book === openBook) ?? allBooks[0]
  const activeContents = activeBook?.contents ?? []

  const sectionRow = (l: OutlineLesson) =>
    l.ready ? (
      <Link
        key={l.id}
        to="/lesson/$id"
        params={{ id: l.id }}
        className="lw-map-sec"
        onClick={() => {
          setMenuOpen(false)
          setNavOpen(false)
        }}
      >
        <b>{l.number}</b>
        <span>{l.title}</span>
      </Link>
    ) : (
      <div key={l.id} className="lw-map-sec off">
        <b>{l.number}</b>
        <span>{l.title}</span>
      </div>
    )

  const curriculumMap = (
    <div className="lw-map">
      <div className="lw-map-books">
        {outline.map((d) => (
          <div key={d.discipline}>
            <div className={'lw-map-disc ' + d.discipline}>{d.label}</div>
            {d.books.map((b) => {
              const ready = bookLessons(b).filter((l) => l.ready).length
              return (
                <button
                  key={b.book}
                  type="button"
                  className={'lw-map-book' + (activeBook?.book === b.book ? ' active' : '')}
                  onMouseEnter={() => setOpenBook(b.book)}
                  onFocus={() => setOpenBook(b.book)}
                  onClick={() => setOpenBook(b.book)}
                >
                  <span>{b.title}</span>
                  <small>{ready ? t.ready(ready) : t.comingSoon}</small>
                </button>
              )
            })}
          </div>
        ))}
      </div>
      <div className="lw-map-detail">
        {activeContents
          .filter((n): n is Extract<OutlineNode, { kind: 'chapter' }> => n.kind === 'chapter')
          .map((ch) => ({ ch, secs: ch.lessons.filter((l) => /^\d+\.\d+$/.test(l.number)) }))
          .filter(({ secs }) => secs.length > 0)
          .map(({ ch, secs }) => (
            <div key={ch.id} className="lw-map-chapter">
              <h4>{ch.label}</h4>
              <div className="lw-map-secs">{secs.map(sectionRow)}</div>
            </div>
          ))}
      </div>
    </div>
  )

  return (
    <div className="lw-page">
      <button
        type="button"
        className={'lw-scrim' + (navOpen ? ' show' : '')}
        aria-label={t.closeMenu}
        tabIndex={navOpen ? 0 : -1}
        onClick={() => setNavOpen(false)}
      />
      <aside className={'lw-drawer' + (navOpen ? ' open' : '')} aria-hidden={!navOpen}>
        <div className="lw-drawer-books">{curriculumMap}</div>
        <div className="lw-drawer-ctas">
          <button type="button" className="lw-btn ghost" onClick={switchLocale}>
            {t.langButton}
          </button>
          <Link to="/login" className="lw-btn ghost" onClick={() => setNavOpen(false)}>
            {t.signIn}
          </Link>
          <Link to="/learn" className="lw-btn solid" onClick={() => setNavOpen(false)}>
            {t.startFree}
          </Link>
        </div>
      </aside>

      <header className="lw-nav" ref={navRef}>
        <div className="lw-nav-inner">
          <Link to="/" className="lw-brand">
            <img src="/logo-mark.png" alt="" width={34} height={34} />
            <span className="lw-brand-name">
              Lemma<em>Deck</em>
              <small>{t.brandSub}</small>
            </span>
          </Link>
          <nav className="lw-nav-links">
            <button
              type="button"
              className={'lw-nav-link dropdown' + (menuOpen ? ' open' : '')}
              aria-expanded={menuOpen}
              aria-haspopup="menu"
              onClick={() => setMenuOpen((v) => !v)}
            >
              {t.navMap}
            </button>
          </nav>
          <div className="lw-nav-actions">
            <button type="button" className="lw-lang" onClick={switchLocale}>
              {t.langButton}
            </button>
            <Link to="/login" className="lw-btn ghost">
              {t.signIn}
            </Link>
          </div>
          <button
            type="button"
            className="lw-burger"
            aria-label={navOpen ? t.closeMenu : t.openMenu}
            aria-expanded={navOpen}
            onClick={() => setNavOpen((v) => !v)}
          >
            {navOpen ? <X size={20} /> : <Menu size={20} />}
          </button>
        </div>
        {menuOpen && (
          <div className="lw-mega" role="menu">
            {curriculumMap}
          </div>
        )}
      </header>

      <main className="lw-content">
        {/* The argument on the left, the product on the right. The galaxy keeps
            its dark skin — the one dark surface on a white page. */}
        <section className="lw-hero">
          <div className="lw-hero-copy">
            <h1>{t.h1}</h1>
            <p className="lw-lead">{t.lead}</p>
            <p className="lw-body">{t.body}</p>
            <p className="lw-outcome">{t.outcome}</p>
            <div className="lw-ctas">
              <Link to="/learn" className="lw-btn solid lg">
                {t.startFree}
              </Link>
            </div>
          </div>

          <div className="lw-hero-galaxy">
            <div className="lw-galaxy-frame">
              <KnowledgeGalaxy
                locale={locale}
                theme="dark"
                bare
                edgeBoost={3.2}
                apiRef={galaxyRef}
                onReady={() => setMapReady(true)}
              />
              {!mapReady && (
                <div className="lw-galaxy-skeleton" aria-hidden>
                  <span />
                </div>
              )}
              <div className={'lw-galaxy-zoom' + (mapReady ? '' : ' hidden')}>
                <button type="button" aria-label={t.zoomIn} onClick={() => galaxyRef.current?.zoomBy(0.78)}>
                  <Plus size={15} />
                </button>
                <button type="button" aria-label={t.zoomOut} onClick={() => galaxyRef.current?.zoomBy(1.28)}>
                  <Minus size={15} />
                </button>
              </div>
            </div>
            <div className="lw-hero-galaxy-foot">
              <p className="lw-hero-galaxy-hint">{t.mapHint}</p>
              <div className="lw-search">
                <Search size={14} aria-hidden />
                <input
                  type="search"
                  value={query}
                  placeholder={t.searchPlaceholder}
                  onChange={(e) => setQuery(e.target.value)}
                  aria-label={t.searchPlaceholder}
                />
                {matches.length > 0 && (
                  <div className="lw-search-pop" role="listbox">
                    {matches.map(({ star, index }) => (
                      <button
                        key={star.id}
                        type="button"
                        role="option"
                        aria-selected="false"
                        onClick={() => {
                          galaxyRef.current?.focusStar(index)
                          setQuery('')
                        }}
                      >
                        <span>{locale === 'zh' ? star.title : (star.titleEn ?? star.title)}</span>
                        <i className={star.discipline} />
                      </button>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </div>
        </section>

        <blockquote className="lw-quote">
          <p>{t.quote}</p>
          <cite>
            {t.quoteBy}
            <span className="lw-quote-title">{t.quoteByTitle}</span>
          </cite>
        </blockquote>

        <section className="lw-points">
          <h2>{t.pointsTitle}</h2>
          <ol>
            {t.points.map((p, i) => (
              <li key={p}>
                <span className="lw-point-n">{String(i + 1).padStart(2, '0')}</span>
                <p>{p}</p>
              </li>
            ))}
          </ol>
        </section>

        <section className="lw-cta">
          <h2>{t.ctaTitle}</h2>
          <div className="lw-ctas">
            <Link to="/learn" className="lw-btn solid lg">
              {t.startFree}
            </Link>
            <button type="button" className="lw-btn ghost lg" onClick={() => setMenuOpen(true)}>
              {t.ctaSecondary}
            </button>
          </div>
        </section>
      </main>
    </div>
  )
}
