import { describe, it, expect, beforeAll, afterAll } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import postgres from 'postgres'

// Integration tests against the Azure easy-app Postgres (the project's runtime DB).
// Loads EASYAPP_DATABASE_URL from repo-root .env.
let sql: ReturnType<typeof postgres>

beforeAll(() => {
  const envText = readFileSync(resolve(__dirname, '../../../../.env'), 'utf8')
  const env = Object.fromEntries(
    envText
      .split('\n')
      .map((l) => l.match(/^([A-Z0-9_]+)=(.*)$/))
      .filter(Boolean)
      .map((m) => [m![1], m![2]]),
  )
  sql = postgres(env.EASYAPP_DATABASE_URL, {
    ssl: 'require',
    max: 2,
    connection: { search_path: '"stemrobin-schema"' },
  })
})
afterAll(async () => {
  await sql.end()
})

describe('sr_users seed', () => {
  it('has the preset learner with a hashed (non-plaintext) password', async () => {
    const rows = await sql`select user_id, email, password_hash from sr_users where user_id = 1`
    expect(rows.length).toBe(1)
    expect(rows[0].email).toBe('edwinbiz@hotmail.com')
    expect(rows[0].password_hash.startsWith('scrypt$')).toBe(true)
    expect(rows[0].password_hash).not.toContain('123456')
  })
})

describe('sr_questions data shape (math-s3-03, generated by the new cap)', () => {
  it('choice items have valid options + exactly one in-range correct_index; work items have none', async () => {
    const rows = await sql`
      select ord, answer_mode, options, correct_index, prompt, answer
      from sr_questions where lesson_id = 'math-s3-03' order by ord`
    expect(rows.length).toBeGreaterThanOrEqual(8)
    for (const q of rows) {
      expect(q.prompt).toBeTruthy()
      expect(q.answer).toBeTruthy()
      if (q.answer_mode === 'choice') {
        expect(Array.isArray(q.options)).toBe(true)
        expect(q.options.length).toBeGreaterThanOrEqual(2)
        expect(Number.isInteger(q.correct_index)).toBe(true)
        expect(q.correct_index).toBeGreaterThanOrEqual(0)
        expect(q.correct_index).toBeLessThan(q.options.length)
      } else {
        expect(q.answer_mode).toBe('work')
        expect(q.options).toBeNull()
        expect(q.correct_index).toBeNull()
      }
    }
    // spec: most items are choice
    const choice = rows.filter((r) => r.answer_mode === 'choice')
    expect(choice.length).toBeGreaterThan(0)
  })
})

describe('answer-event traceability (D2 weakness analysis)', () => {
  it('a wrong choice answer for the learner is recorded and retrievable', async () => {
    const [q] = await sql`
      select id, correct_index, (options->>0) as first
      from sr_questions where lesson_id='math-s3-03' and answer_mode='choice' order by ord limit 1`
    // pick a definitely-wrong option index
    const wrong = q.correct_index === 0 ? 1 : 0
    const isCorrect = wrong === q.correct_index
    const [ins] = await sql`
      insert into sr_answer_events (user_id, question_id, is_correct, chosen)
      values (1, ${q.id}, ${isCorrect}, ${wrong}) returning id`
    try {
      const wrongForLearner = await sql`
        select e.id, e.question_id, e.chosen from sr_answer_events e
        where e.user_id = 1 and e.is_correct = false and e.id = ${ins.id}`
      expect(wrongForLearner.length).toBe(1)
      expect(wrongForLearner[0].question_id).toBe(q.id)
    } finally {
      await sql`delete from sr_answer_events where id = ${ins.id}`
    }
  })
})
